name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: ./.github/test.sh
      env:
        LARK_APP_NO_PERMISSION_APP_ID: ${{ secrets.LARK_APP_NO_PERMISSION_APP_ID }}
        LARK_APP_NO_PERMISSION_APP_SECRET: ${{ secrets.LARK_APP_NO_PERMISSION_APP_SECRET }}
        LARK_APP_ALL_PERMISSION_APP_ID: ${{ secrets.LARK_APP_ALL_PERMISSION_APP_ID }}
        LARK_APP_ALL_PERMISSION_APP_SECRET: ${{ secrets.LARK_APP_ALL_PERMISSION_APP_SECRET }}
        LARK_USER_ADMIN_USER_ID: ${{ secrets.LARK_USER_ADMIN_USER_ID }}
        LARK_USER_ADMIN_OPEN_ID: ${{ secrets.LARK_USER_ADMIN_OPEN_ID }}
        LARK_USER_ADMIN_NAME: ${{ secrets.LARK_USER_ADMIN_NAME }}
        LARK_CHAT_CONTAINS_APP_PERMISSION_APP_CHAT_ID: ${{ secrets.LARK_CHAT_CONTAINS_APP_PERMISSION_APP_CHAT_ID }}
        LARK_CHAT_NOT_CONTAINS_APP_PERMISSION_APP_CHAT_ID: ${{ secrets.LARK_CHAT_NOT_CONTAINS_APP_PERMISSION_APP_CHAT_ID }}
        LARK_CHAT_FOR_SEND_MSG_CHAT_ID: ${{ secrets.LARK_CHAT_FOR_SEND_MSG_CHAT_ID }}
        LARK_FILE_KEY_TEST_FILE_1_PNG: ${{ secrets.LARK_FILE_KEY_TEST_FILE_1_PNG }}
        LARK_FILE_KEY_TEST_FILE_2_DOC: ${{ secrets.LARK_FILE_KEY_TEST_FILE_2_DOC }}
        LARK_MESSAGE_ADMIN_SEND_TEST_IN_CHAT_CONTAINS_ALL_PERMISSION_APP: ${{ secrets.LARK_MESSAGE_ADMIN_SEND_TEST_IN_CHAT_CONTAINS_ALL_PERMISSION_APP }}
        LARK_MESSAGE_ADMIN_SEND_IMAGE_IN_CHAT_CONTAINS_ALL_PERMISSION_APP: ${{ secrets.LARK_MESSAGE_ADMIN_SEND_IMAGE_IN_CHAT_CONTAINS_ALL_PERMISSION_APP }}
        LARK_MESSAGE_ALL_PERMISSION_APP_SEND_TEXT_IN_CHAT_CONTAINS_ALL_PERMISSION_APP: ${{ secrets.LARK_MESSAGE_ALL_PERMISSION_APP_SEND_TEXT_IN_CHAT_CONTAINS_ALL_PERMISSION_APP }}

    - name: Upload Cov
      run: bash <(curl -s https://codecov.io/bash)
